AllCops:
  Include:
    - Rakefile
Layout/SpaceBeforeFirstArg:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SignalException:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
